### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Error! This token is not acceptable!

### ISSUE THREAD

**Issue by RC047** [phaticusthiccy/TextMaker-Unlimited#2]
(node:1286) UnhandledPromiseRejectionWarning: Error: Error! This token is not acceptable!                               at Object.textpro (/data/data/com.termux/files/home/node_modules/textmaker-thiccy/lib/textmaker/textpro.js:83:22)

**Comment by phaticusthiccy** [comment]
Can you provide which html link you used?

**Comment by phaticusthiccy** [comment]
Closed İnactivity.
