### ISSUE TITLE
(node:19452) UnhandledPromiseRejectionWarning: TypeError: form.getBuffer is not a function

### ISSUE THREAD

**Issue by viniciusgdr** [phaticusthiccy/TextMaker-Unlimited#3]

**Comment by phaticusthiccy** [comment]
Hi @viniciusgdr 

You must provide your whole code.

**Comment by Sew01RavinduManoj01KingAndQueen** [comment]
JSON.parse(token2[1]),
                                    ^

 TypeError: Cannot read property '1' of null



can you tell how to fix this error for ephoto api

**Comment by phaticusthiccy** [comment]
> JSON.parse(token2[1]),
> ^
> 
> TypeError: Cannot read property '1' of null
> 
> can you tell how to fix this error for ephoto api

Ephoto module not working.
