### ISSUE TITLE
token is not acceptable

### ISSUE THREAD

**Issue by iluser** [phaticusthiccy/TextMaker-Unlimited#4]
i try to use a different url but i got Error: Error! This token is not acceptable!

sample code
```
const thiccysapi = require('textmaker-thiccy');

thiccysapi.textpro("https://textpro.me/create-realistic-cloud-text-effect-online-free-999.html",
    "Phaticusthiccy"
    ).then(async (data) => { 
      try { 
          console.log(data)
      } catch(err) { 
          console.log(err)
      } 
});
```

response
`(node:1) UnhandledPromiseRejectionWarning: Error: Error! This token is not acceptable!
    at Object.textpro (/app/available_modules/1624961831000/textmaker-thiccy/lib/textmaker/textpro.js:83:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by phaticusthiccy** [comment]
Duplicate #2

**Comment by phaticusthiccy** [comment]
Hi @iluser 

Some Textpro tools more complicated than other simply tools. I chech your html page and ı saw the choose options in the this tool. 

My Textmaker Unlimited API was not developed to do this. You can try more simple tools until i fix it.
